### ISSUE TITLE
select options should be displayed in an alphabetical order by default

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#1]
The library offers `select` field type from `buildFieldSchema` and currently it is display all the select options in an unordered list. To somehow improve the user experience, the select options should be in an alphabetical order by default. This is specially useful when there are a lot of options to choose from.

**Comment by ChronicStone** [comment]
Alphabetical sorting can be a significant issue to handle at the library level. Select option is pretty complex and has different rendering options. Here are for example 3 different things that can be passed as option value :

- **Case 1 : plain string | raw :**
```
['Value1', 'Value2', ...]
```

- **Case 2 : Non-string primitive | raw :**
```
[1, 23213, true, 021023, false, ...]
```

- **Case 3 : any value | label/value pair | raw string label**
```
[
  { label: "value 1", value: 1 },
  { label: "value 2", value: 2 },
  ...
]
```

- **Case 4 : any valueL label/value pair | render funct. label**
```
[
  {
    label: (...) => <div>This is <strong>{value}</strong></div>, 
    value: "21923919421"
  }
]
```

The issue here is that
1. What needs to be sorted can actually be quite different from a case to an other
2. Case 4 would require JSX parsing to extract text bits only (edge case, but feels really clunky) ...
3. On case label/values pair are passed, on some cases you'd want to sort using value, on other you'd want to sort using labels

Additionally, default alpha sorting isn't an ideal behaviour, isn't always relevant/practical.
This is outside of the library responsability scope. App code is responsible for providing options / option resolvers. Any kind of formatting / sorting / manipulation should be achieved here.
