### ISSUE TITLE
Inconsistent behavior for group input type

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#2]
Currently we use `group` field type from `buildFieldSchema` as a way to display phone number input field where user can select country code and enter masked phone number. However there are several issues we found so far that needed to be addressed:

1. Setting property `required: true` is not working. User still able to submit the form even having the input field empty.
2. The `fieldParams.mask` seems auto adding the value from the dependency. If it is possible we can avoid it or make an option property where we can specify wether we want it or not. Additionally, user can only enter numbers.

**Comment by ChronicStone** [comment]
The required part is pretty straight forward. However, I'm not sure to fully understand what you mean in 2) here. Can you add a bit of extra context ? Like an example of what's the current behaviour you're getting, and what you're expecting it to be ?

**Comment by jesephan** [comment]
Hi @ChronicStone related to 2) issue here is the [sample schema](https://pastebin.com/LEJTT0CX), Additionally here is the [Video Link](https://www.dropbox.com/scl/fi/lib5l6bvnsdnihq4gve3k/mask-issue.mp4?rlkey=rqjuk2u9bq742wyuzefgrkd8g&dl=0) where you can see it how it happen

**Comment by ChronicStone** [comment]
@jesephan Okay got it.

So here again we're out of the library scope. This phone number imput is a kind of custom input built around the input group. The issue here isn't related to how the mask works (fyi, it uses [Maska](https://beholdr.github.io/maska/#/?id=tokens) intenally so if you want mask docs, refer to it), but rather to how I implemented this phone number input.

```json
{
  "AC": "+247 ####",
  "AD": "+376 ### ###",
  "AE": "+971 # ### ####",
  "AF": "+93 ## ### ####",
  "AG": "+1(268)### ####",
  "AI": "+1(264)### ####",
  "AL": "+355(###)### ###",
  "AM": "+374 ## ### ###",
  "AN": "+599 9### ####",
  "AO": "+244(###)### ###",
  "AQ": "+672 1## ###",
  ...
}
```

The way it works is that I used a list of format masks associated to each coutry code, but the masks themself include the country indicative number. On this particular case, we're kind of reaching the limits of what can be done with a schema-based custom input. 

If you want to have better control on the logic, differently mask the input ...etc, then you might want to create a custom component for this, that ships its own logic, and use that as a "custom-component" field on your form schema.

For reference, here's a very well made / complete vue phone number input you can take as reference : 
https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input

Grouped inputs & masks are meant to handle relatively simple stuff, so if you want a phone number input with a better UX, I suggest you either wrap the one I mentionned above in a custom component & use its theming API to match you app theme, or directly take a look at how it's built & write one that uses naive-ui components for the UI part

**Comment by ChronicStone** [comment]
@jesephan About the required property, it is actually working as expected, but with the a few specificities to keep in mind : 

Group fields produce an object by default. On the case of the phone number input, here's what's the default produced value type looks like : 

<img width="338" alt="image" src="https://github.com/ChronicStone/vue-sweettools/assets/55083156/87b0f07a-e615-41d3-91a8-d554986ca563">

In order to get a plain string, the `transform` property will make sure the form outputs only the string value we're expecting. But the issue in this case is that transformers runs when the form is submitted, after validation. 

On this case, that means the required validator runs on the object { countryCode: '', phoneValue: '' } and not the empty phoneValue string.

To validate the input, you can do this : 
1. Set required on the "group" field, to still get the asterisk
2. Set required on the child fields as well (Make sure you use latest version of the lib). Child validators will apply to the parent
3. You can play with child label fields if you want to change field name in error message

Here's a live example of that : 
https://stackblitz.com/edit/vite-t6hfv7?file=src%2FApp.vue
