### ISSUE TITLE
Incorrect searchQuery fields submitted to Api

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#9]
SweetTools version: 0.4.4

The issue happens when user try to use search functionality with the following table schema setup:
`remote: true,searchQuery: ["email"]`

The payload that is being submitted to the backend is like this:
```
{
    "value": "an",
    "fields": [
        "fullName",
        "credentials.email"
    ]
}
```

Currently, it will show incorrect results since it is supposed to be only searching for email but there is fullname included. Here is the [link to the issue demo](https://drive.google.com/file/d/1KtB8fOu0EGePJ-l7JOWmAUkc-v4uLd0Y/view?usp=sharing).

**Comment by ChronicStone** [comment]
Hi @jesephan,  you're simply not looking at the right schema. The schema you showed that only has "email" is the invitation table schema, and the table you're showing on the UI is the users table, not the invitation table.

For this kind of issues, rather than a video, try to do a live minimal reproduction of the issue of stackblitz / codesandbox & put the link with the issue. That will allow first on your end to see if it's really a lib issue or if it's on your end, and it'll also help me identify a lot faster what the actual issue is if there's one.

I don't have access to the manager's codebase anymore, which makes debugging this kind of things pretty time-consuming & hard. If you need to, I can provide a sweettools form / table template on codesandbox that you can use as a base for this kind of issues 😄

**Comment by jesephan** [comment]
@ChronicStone but you see in the video that the table header only shows email with search icon. That means that the email is the only searchable column or field. But yeah maybe i just mistakenly show the incorrect schema or open incorrect file. I'll check again probably tomorrow. apologized for that. I will try to create reproduction code next time. thanks @ChronicStone!

**Comment by jesephan** [comment]
I'm closing this @ChronicStone you are right I made a mistake looking at the wrong schema. Moving forward I will make sure to double check and provide reproduction of the issue.
